[project]
name = "repaudit"
version = "0.0.1"
description = "A cli-package to view requirements of a project as a DAG"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click~=8.3",
    "httpx~=0.28",
    "matplotlib~=3.10",
    "networkx~=3.6",
    "packaging~=26.0",
    "pydot~=4.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
repaudit = "repaudit.main:cli"
